@REST_DotNET_Coffee_Android_HostAddress = https://localhost:7066

GET {{REST_DotNET_Coffee_Android_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{REST_DotNET_Coffee_Android_HostAddress}}/weatherforecast

###
